/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as VisitorRouteImport } from './routes/visitor'
import { Route as VisitorDashboardRouteImport } from './routes/visitorDashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRoute = VisitorRouteImport.update({
  id: '/visitor',
  path: '/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorDashboardRoute = VisitorDashboardRouteImport.update({
  id: '/visitorDashboard',
  path: '/visitorDashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/visitor': typeof VisitorRoute
  '/visitorDashboard': typeof VisitorDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/visitor': typeof VisitorRoute
  '/visitorDashboard': typeof VisitorDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/visitor': typeof VisitorRoute
  '/visitorDashboard': typeof VisitorDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/visitor' | '/visitorDashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/visitor' | '/visitorDashboard'
  id: '__root__' | '/' | '/history' | '/visitor' | '/visitorDashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  VisitorRoute: typeof VisitorRoute
  VisitorDashboardRoute: typeof VisitorDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor': {
      id: '/visitor'
      path: '/visitor'
      fullPath: '/visitor'
      preLoaderRoute: typeof VisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitorDashboard': {
      id: '/visitorDashboard'
      path: '/visitorDashboard'
      fullPath: '/visitorDashboard'
      preLoaderRoute: typeof VisitorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  VisitorRoute: VisitorRoute,
  VisitorDashboardRoute: VisitorDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
